# Generated by Django 5.0.6 on 2024-05-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapato_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='imagen',
            field=models.ImageField(upload_to='static/imga'),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='ubicacion',
            field=models.CharField(max_length=20),
        ),
    ]
